# Generated by Django 5.0.6 on 2024-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[("Consultation", "Consultation"), ("Follow-up", "Follow-up"), ("Health Check-up", "Health Check-up"), ("Vaccination", "Vaccination"), ("Lab Test", "Lab Test"), ("Pediatric Checkup", "Pediactric Checkup")], default="Consultation", max_length=50),
        ),
    ]
