# Generated by Django 5.0.6 on 2024-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[("10:00 AM", "10:00 AM"), ("10:30 AM", "10:30 AM"), ("11:00 AM", "11:00 AM"), ("11:30 AM", "11:30 AM"), ("1:00 PM", "1:00 PM"), ("1:30 PM", "1:30 PM"), ("2:00 PM", "2:00 PM"), ("2:30 PM", "2:30 PM"), ("3:00 PM", "3:00 PM"), ("3:30 PM", "3:30 PM"), ("4:00 PM", "4:00 PM"), ("4:30 PM", "4:30 PM"), ("5:00 PM", "5:00 PM"), ("5:30 PM", "5:30 PM")], default="10:00 AM", max_length=14),
        ),
    ]
